# Generated by Django 2.2.12 on 2021-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantPhotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantphotos',
            name='text',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
