# Generated by Django 2.2.12 on 2021-10-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantPhotos', '0002_restaurantphotos_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantphotos',
            old_name='text',
            new_name='value',
        ),
    ]
