# Generated by Django 2.2.12 on 2021-10-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalApp', '0003_why'),
    ]

    operations = [
        migrations.DeleteModel(
            name='why',
        ),
    ]
