# Generated by Django 2.2.12 on 2021-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('quotes', models.TextField(max_length=250)),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
    ]
